layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
      - safiyat.github.io
      - parse_results.eci.in
      - hyper-conf
      - alacritty-conf
      - aria2conf
      - kde-conf
      - terminator-conf
      - foobar2000conf

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: rezasafiyat
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 2715348
  # telegram: your_username
  twitter: reza_safiyat
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Software-defined Networking
    web_url: https://github.com/topics/sdn
    image_url: https://software.intel.com/content/dam/develop/public/us/en/images/logos/logo-dpdk-02-16x9.png.rendition.intel.web.480.270.png

theme: jekyll-theme-minimal
